<?php
/**
 * @category   Bsc
 * @package    Bsc_DrugTest
 * @author     web@bodyscience.com.au
 * @copyright  This file was generated by using Module Creator(http://code.vky.co.in/magento-2-module-creator/) provided by VKY <viky.031290@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

namespace Bsc\DrugTest\Controller\Index;

use Magento\Framework\App\Action\Context;
use Magento\Framework\Exception\NotFoundException;
use Bsc\DrugTest\Block\DrugTestView;

class View extends \Magento\Framework\App\Action\Action
{
	protected $_drugtestview;

	public function __construct(
        Context $context,
        DrugTestView $drugtestview
    ) {
        $this->_drugtestview = $drugtestview;
        parent::__construct($context);
    }

	public function execute()
    {
    	if(!$this->_drugtestview->getSingleData()){
    		throw new NotFoundException(__('Parameter is incorrect.'));
    	}
    	
        $this->_view->loadLayout();
        $this->_view->getLayout()->initMessages();
        $this->_view->renderLayout();
    }
}
