<?php
/**
 * @category   Bsc
 * @package    Bsc_DrugTest
 * @author     web@bodyscience.com.au
 * @copyright  This file was generated by using Module Creator(http://code.vky.co.in/magento-2-module-creator/) provided by VKY <viky.031290@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

namespace Bsc\DrugTest\Block;

use Magento\Framework\View\Element\Template\Context;
use Bsc\DrugTest\Model\DrugTestFactory;
use Magento\Cms\Model\Template\FilterProvider;
/**
 * DrugTest View block
 */
class DrugTestView extends \Magento\Framework\View\Element\Template
{
    /**
     * @var DrugTest
     */
    protected $_drugtest;
    public function __construct(
        Context $context,
        DrugTestFactory $drugtest,
        FilterProvider $filterProvider
    ) {
        $this->_drugtest = $drugtest;
        $this->_filterProvider = $filterProvider;
        parent::__construct($context);
    }

    public function _prepareLayout()
    {
        $this->pageConfig->getTitle()->set(__('Bsc DrugTest Module View Page'));
        
        return parent::_prepareLayout();
    }

    public function getSingleData()
    {
        $id = $this->getRequest()->getParam('id');
        $drugtest = $this->_drugtest->create();
        $singleData = $drugtest->load($id);
        if($singleData->getDrugTestId() && $singleData->getStatus() == 1){
            return $singleData;
        }else{
            return false;
        }
    }
}