<?php
/**
 * @category   Bsc
 * @package    Bsc_DrugTest
 * @author     web@bodyscience.com.au
 * @copyright  This file was generated by using Module Creator(http://code.vky.co.in/magento-2-module-creator/) provided by VKY <viky.031290@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

namespace Bsc\DrugTest\Block;

use Magento\Framework\View\Element\Template\Context;
use Bsc\DrugTest\Model\DrugTestFactory;
/**
 * DrugTest List block
 */
class DrugTestListData extends \Magento\Framework\View\Element\Template
{
    /**
     * @var DrugTest
     */
    protected $_drugtest;
    public function __construct(
        Context $context,
        DrugTestFactory $drugtest
    ) {
        $this->_drugtest = $drugtest;
        parent::__construct($context);
    }

    public function _prepareLayout()
    {
        $this->pageConfig->getTitle()->set(__('Drug Test Results'));
        
        if ($this->getDrugTestCollection()) {
            $pager = $this->getLayout()->createBlock(
                'Magento\Theme\Block\Html\Pager',
                'bsc.drugtest.pager'
            )->setAvailableLimit(array(5=>5,10=>10,15=>15))->setShowPerPage(false)->setCollection(
                $this->getDrugTestCollection()
            );
            $this->setChild('pager', $pager);
            $this->getDrugTestCollection()->load();
        }
        return parent::_prepareLayout();
    }

    public function getDrugTestCollection()
    {
        $page = ($this->getRequest()->getParam('p'))? $this->getRequest()->getParam('p') : 1;
        $pageSize = ($this->getRequest()->getParam('limit'))? $this->getRequest()->getParam('limit') : 5;

        $drugtest = $this->_drugtest->create();
        $collection = $drugtest->getCollection();
        $collection->addFieldToFilter('status','1');
        //$drugtest->setOrder('drugtest_id','ASC');
        //$collection->setPageSize($pageSize);
        //$collection->setCurPage($page);

        return $collection;
    }

    public function getPagerHtml()
    {
        return $this->getChildHtml('pager');
    }
}