<?php
/**
 * @category   Bsc
 * @package    Bsc_DrugTest
 * @author     web@bodyscience.com.au
 * @copyright  This file was generated by using Module Creator(http://code.vky.co.in/magento-2-module-creator/) provided by VKY <viky.031290@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

namespace Bsc\DrugTest\Controller\Adminhtml\Items;


use Magento\Framework\App\Filesystem\DirectoryList;


class Save extends \Bsc\DrugTest\Controller\Adminhtml\Items
{


    public function execute()
    {
        if ($this->getRequest()->getPostValue()) {
            $model = $this->_objectManager->create('Bsc\DrugTest\Model\DrugTest');
            $data = $this->getRequest()->getPostValue();

            try {

                if(isset($_FILES['image']['name']) && $_FILES['image']['name'] != '') {
                    try{
                        $uploaderFactory = $this->uploaderFactory->create(['fileId' => 'image']);
                        $uploaderFactory->setAllowedExtensions(['pdf', 'doc']);
                        $imageAdapter = $this->adapterFactory->create();
                        //$uploaderFactory->addValidateCallback('custom_image_upload',$imageAdapter,'validateUploadFile');
                        $uploaderFactory->setAllowRenameFiles(true);
                        $uploaderFactory->setFilesDispersion(true);
                        $mediaDirectory = $this->filesystem->getDirectoryRead(DirectoryList::MEDIA);
                        $destinationPath = $mediaDirectory->getAbsolutePath('bsc/drugtest');
                        $result = $uploaderFactory->save($destinationPath);
                        if (!$result) {
                            throw new LocalizedException(
                                __('File cannot be saved to path: $1', $destinationPath)
                            );
                        }

                        $imagePath = 'bsc/drugtest'.$result['file'];
                        $data['image'] = $imagePath;

                    } catch (\Exception $e) {
                        $this->messageManager->addError(
                            __('Something went wrong while saving the item data. Please review the error log.')
                        );
                    }

                }



                if(isset($data['image']['delete']) && $data['image']['delete'] == 1) {
                    $mediaDirectory = $this->filesystem->getDirectoryRead(DirectoryList::MEDIA)->getAbsolutePath();
                    $file = $data['image']['value'];
                    $imgPath = $mediaDirectory.$file;
                    if ($this->_file->isExists($imgPath))  {
                        $this->_file->deleteFile($imgPath);
                    }
                    $data['image'] = NULL;

                }
                if (isset($data['image']['value'])){
                    $data['image'] = $data['image']['value'];

                }
                $inputFilter = new \Zend_Filter_Input(
                    [],
                    [],
                    $data
                );
                $data = $inputFilter->getUnescaped();
                $id = $this->getRequest()->getParam('id');
                if ($id) {
                    $model->load($id);
                    if ($id != $model->getId()) {
                        throw new \Magento\Framework\Exception\LocalizedException(__('The wrong item is specified.'));
                    }

                }

                $model->setData($data);

                $session = $this->_objectManager->get('Magento\Backend\Model\Session');
                $session->setPageData($model->getData());
                $model->save();
                $this->messageManager->addSuccess(__('You saved the item.'));

                $session->setPageData(false);
                if ($this->getRequest()->getParam('back')) {
                    $this->_redirect('bsc_drugtest/*/edit', ['id' => $model->getId()]);
                    return;
                }
                $this->_redirect('bsc_drugtest/*/');
                return;

            } catch (\Magento\Framework\Exception\LocalizedException $e) {
                $this->messageManager->addError($e->getMessage());
                $id = (int)$this->getRequest()->getParam('id');
                if (!empty($id)) {
                    $this->_redirect('bsc_drugtest/*/edit', ['id' => $id]);
                } else {
                    $this->_redirect('bsc_drugtest/*/new');
                }
                return;
            } catch (\Exception $e) {
                $this->messageManager->addError(
                    __('Something went wrong while saving the item data. Please review the error log.')
                );
                $this->_objectManager->get('Psr\Log\LoggerInterface')->critical($e);
                $this->_objectManager->get('Magento\Backend\Model\Session')->setPageData($data);
                $this->_redirect('bsc_drugtest/*/edit', ['id' => $this->getRequest()->getParam('id')]);
                return;
            }
        }


        $this->_redirect('bsc_drugtest/*/');
    }
}
