<?php
/**
 * @category   Bsc
 * @package    Bsc_DrugTest
 * @author     web@bodyscience.com.au
 * @copyright  This file was generated by using Module Creator(http://code.vky.co.in/magento-2-module-creator/) provided by VKY <viky.031290@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

namespace Bsc\DrugTest\Block\Adminhtml\Items\Edit\Tab;

use Magento\Backend\Block\Widget\Form\Generic;
use Magento\Backend\Block\Widget\Tab\TabInterface;

class Main extends Generic implements TabInterface
{
    protected $_wysiwygConfig;

    public function __construct(
        \Magento\Backend\Block\Template\Context $context,
        \Magento\Framework\Registry $registry,
        \Magento\Framework\Data\FormFactory $formFactory,
        \Magento\Cms\Model\Wysiwyg\Config $wysiwygConfig,
        array $data = []
    )
    {
        $this->_wysiwygConfig = $wysiwygConfig;
        parent::__construct($context, $registry, $formFactory, $data);
    }

    /**
     * {@inheritdoc}
     */
    public function getTabLabel()
    {
        return __('Drug Test Information');
    }

    /**
     * {@inheritdoc}
     */
    public function getTabTitle()
    {
        return __('Drug Test Information');
    }

    /**
     * {@inheritdoc}
     */
    public function canShowTab()
    {
        return true;
    }

    /**
     * {@inheritdoc}
     */
    public function isHidden()
    {
        return false;
    }

    /**
     * Prepare form before rendering HTML
     *
     * @return $this
     * @SuppressWarnings(PHPMD.NPathComplexity)
     * @SuppressWarnings(PHPMD.ExcessiveMethodLength)
     */
    protected function _prepareForm()
    {
        $model = $this->_coreRegistry->registry('current_bsc_drugtest_items');
        /** @var \Magento\Framework\Data\Form $form */
        $form = $this->_formFactory->create();
        $form->setHtmlIdPrefix('item_');
        $fieldset = $form->addFieldset('base_fieldset', ['legend' => __('Drug Test Information')]);
        if ($model->getId()) {
            $fieldset->addField('drugtest_id', 'hidden', ['name' => 'drugtest_id']);
        }
        $fieldset->addField(
            'product',
            'text',
            ['name' => 'product', 'label' => __('Product'), 'title' => __('Product'), 'required' => true]
        );
        $fieldset->addField(
            'product_sku',
            'text',
            ['name' => 'product_sku', 'label' => __('Product SKU'), 'title' => __('Product SKU'), 'required' => true]
        );
        $fieldset->addField(
            'flavour',
            'text',
            ['name' => 'flavour', 'label' => __('Flavour'), 'title' => __('Flavour'), 'required' => true]
        );
        $fieldset->addField(
            'batch',
            'text',
            ['name' => 'batch', 'label' => __('Batch'), 'title' => __('Batch'), 'required' => true]
        );

        $fieldset->addField(
            'expiry',
            'date',
            ['name' => 'expiry', 'date_format' => 'dd-MM-yyyy', 'label' => __('Expiry/BB'), 'title' => __('Expiry/BB'), 'required' => true]
        );
        $fieldset->addField(
            'certificate_date',
            'date',
            ['name' => 'certificate_date', 'date_format' => 'dd-MM-yyyy', 'label' => __('Certificate Date'), 'title' => __('Certificate Date'), 'required' => true]
        );

        $fieldset->addField(
            'certify_by',
            'select', array(
            'name' => 'certify_by',
            'label' => __('Certify By'),
            'title' => __('Certify By'),
            'required' => true,
            'values' => array('-1' => 'Please Select..', 'Hasta Certified Product' => 'Hasta Certified Product', 'Hasta - Single Batch Certification' => 'Hasta - Single Batch Certification', 'Informed Sport Certified Product' => 'Informed Sport Certified Product', 'Informed Sport - Single Batch Certification' => 'Informed Sport - Single Batch Certification'),
            'tabindex' => 1
        ));

        $fieldset->addField(
            'testing_schedule',
            'select', array(
            'name' => 'testing_schedule',
            'label' => __('Testing Schedule'),
            'title' => __('Testing Schedule'),
            'required' => true,
            'values' => array('-1' => 'Please Select..', 'Every Batch Is Tested Under This Program Prior To Release' => 'Every Batch Is Tested Under This Program Prior To Release', 'This Batch Was Selected For Testing By Bsc' => 'This Batch Was Selected For Testing By Bsc'),
            'tabindex' => 1
        ));

        $fieldset->addField(
            'image',
            'file',
            [
                'name' => 'image',
                'label' => __('Drug Test File:(pdf, doc)'),
                'title' => __('Drug Test File'),
                'required' => true
            ]
        );

        $fieldset->addField(
            'status',
            'select',
            ['name' => 'status', 'label' => __('Status'), 'title' => __('Status'), 'options' => [0 => 'Disable', 1 => 'Enable'], 'required' => true]
        );

        $form->setValues($model->getData());
        $this->setForm($form);
        return parent::_prepareForm();
    }
}
